# Generated by Django 2.2.5 on 2019-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='month',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='todo',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
